import Link from "next/link"
import "./globals.css" //import globals.css
import Image from "next/image"
import "@fortawesome/fontawesome-svg-core/styles.css"  //import fontawesome

export const metadata = {
  title: 'Geels',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* area header */}
        <header>
          {/* area banner */}
          {/* <img src={"../images/logo.png"} alt="logo uti" /> */}
          <Image src={"/images/logo.png"} alt="Logo UTI" width={320} height={60} priority className="mt-6 ml-20 mb-6"></Image>

          {/* area menu */}
          <nav className="mt-5 flex justify-center text-center">
            <Link href={"/"} className="bg-color1 hover:bg-blue-700 text-color2 rounded-full px-5 py-2.5 mr-2 w-52">Data Mahasiswa</Link>
            <Link href={"/"} className="bg-color1 hover:bg-blue-700 text-color2 rounded-full px-5 py-2.5 ml-2 w-52">Log Data Mahasiswa</Link>
          </nav>
        </header>

        {/* area content */}
        <section className="m-5">
          {children}
        </section>

        {/* area footer */}
        <footer className="flex justify-center text-center bg-color1 text-color2 py-15px">
          Copyright &copy; 2024 - Lionel Aditya
        </footer>
      </body>
    </html>
  )
}
